language: python
matrix:
    include:
    - python: "3.5"
before_install:
    - ./install-deps.sh
install:
    - pip install .
    - echo Later... jupyter nbextension install --py --sys-prefix unray
    - echo Later... jupyter nbextension enable --py --sys-prefix unray
script:
    - pushd test && python -m pytest && popd
