language: python
matrix:
    include:
    - python: "3.5"
before_install:
    - ./install-deps.sh
install:
    - pip install .
    - jupyter nbextension install --py --sys-prefix unray
    - jupyter nbextension enable --py --sys-prefix unray
script:
    - ./test.sh
